/**
 * Configuration status, readable without touching the database.
 *
 * Deliberately free of side effects and heavy imports so that pages can render
 * an honest "not configured yet" state instead of a 500 when a deployment is
 * missing its environment. Nothing here throws.
 */

export interface EnvRequirement {
  key: string;
  present: boolean;
  hint: string;
}

function has(key: string): boolean {
  return Boolean(process.env[key]?.trim());
}

/** Sign-in cannot work at all without these. */
export function requiredEnv(): EnvRequirement[] {
  return [
    {
      key: "DATABASE_URL",
      present: has("DATABASE_URL"),
      hint: "Pooled Neon connection string, from the Neon console.",
    },
    {
      key: "BETTER_AUTH_SECRET",
      present: has("BETTER_AUTH_SECRET"),
      hint: "Signing key for sessions: openssl rand -base64 32",
    },
  ];
}

export function googleConfigured(): boolean {
  return has("GOOGLE_CLIENT_ID") && has("GOOGLE_CLIENT_SECRET");
}

export function githubConfigured(): boolean {
  return has("GITHUB_CLIENT_ID") && has("GITHUB_CLIENT_SECRET");
}

/** Email + password needs no third-party credentials, so it is always available. */
export function authReady(): boolean {
  return requiredEnv().every((item) => item.present);
}

export function resendConfigured(): boolean {
  // `EMAIL_DOMAIN` is what the addresses below are built from, so a key alone
  // is not enough. Requiring it is also the accident guard: a deployment that
  // has a key but has not verified a sending domain would otherwise open
  // registration and have Resend refuse every message it then had to send.
  return has("RESEND_API_KEY") && (has("EMAIL_DOMAIN") || has("EMAIL_FROM"));
}

/**
 * The domain every product address sits on. Must be verified in Resend, or the
 * API accepts the key and refuses each individual message.
 */
export function emailDomain(): string {
  return process.env.EMAIL_DOMAIN?.trim() || "docxy.app";
}

/**
 * One sending identity, as `Name <local@domain>`.
 *
 * The mailbox names are fixed rather than each being its own required variable:
 * they are a property of the domain, and an operator who has verified one has
 * already decided all five. Each still takes an override for a deployment whose
 * mail lives somewhere unusual.
 */
function sender(local: string, name: string, override: string | undefined): string {
  const explicit = override?.trim();
  if (explicit) return explicit;
  return `${name} <${local}@${emailDomain()}>`;
}

/**
 * Transactional mail nobody should reply to: the verification link and the
 * organization invitation. Both are machine-sent and answered by clicking, so a
 * reply has nowhere useful to land.
 */
export function emailFrom(): string {
  return sender("no-reply", "Docxy", process.env.EMAIL_FROM);
}

/**
 * The welcome note, sent once an address is confirmed.
 *
 * Separate from the no-reply above because it asks somebody to do three things,
 * and a person who gets stuck on any of them should be able to answer the
 * message rather than hunt for a support address. Replies go to `support@`.
 */
export function onboardingFrom(): string {
  return sender("onboarding", "Docxy", process.env.ONBOARDING_EMAIL_FROM);
}

/**
 * The founder's own address, for mail actually written by a person rather than
 * generated by the product. It signs with a name and invites a reply, so it
 * sends from a mailbox a reply reaches directly.
 */
export function founderFrom(): string {
  return sender("arindam", "Arindam Majumder", process.env.FOUNDER_EMAIL_FROM);
}

/** Where replies to product mail land. */
export function supportAddress(): string {
  return process.env.SUPPORT_EMAIL?.trim() || `support@${emailDomain()}`;
}

/** The address published on the site for anyone not yet a customer. */
export function contactAddress(): string {
  return process.env.CONTACT_EMAIL?.trim() || `contact@${emailDomain()}`;
}

/**
 * Whether this deployment can send transactional mail.
 *
 * Two things depend on it and neither is optional: confirming an address at
 * signup, and inviting somebody to an organization.
 */
export function emailReady(): boolean {
  return resendConfigured();
}

/**
 * Whether new accounts may be created here.
 *
 * Open exactly when this deployment can send a verification email, and closed
 * otherwise - the two facts are one fact. Without verification an address is
 * claimed by whoever types it first, and an organization invitation sent to
 * that address reaches them rather than its owner. Email verification is what
 * closes that, so registration opens with it and not before.
 *
 * This replaces DOCXY_ALLOW_SIGNUP, which asked an operator to promise the same
 * invariant by hand and could be set to 1 on a deployment that could not send a
 * single message.
 */
export function signupOpen(): boolean {
  return emailReady();
}

export function missingEnv(): EnvRequirement[] {
  return requiredEnv().filter((item) => !item.present);
}

/**
 * The origin Better Auth builds callback URLs from. Behind a proxy or tunnel
 * the request origin is not the public one, so an explicit value wins.
 */
export function appUrl(): string | undefined {
  return process.env.BETTER_AUTH_URL?.trim() || process.env.APP_URL?.trim() || undefined;
}

function origin(value: string | undefined): string | undefined {
  const trimmed = value?.trim().replace(/\/+$/, "");
  if (!trimmed) return undefined;
  // Vercel's own variables carry a bare hostname; BETTER_AUTH_URL carries a URL.
  return trimmed.startsWith("http") ? trimmed : `https://${trimmed}`;
}

/**
 * Every origin allowed to complete a sign-in.
 *
 * Better Auth refuses a request whose origin is not `baseURL` or one of these,
 * which is what stops another site from driving this one's auth endpoints. That
 * default is right and it is also why one deployment can have several names:
 * this app answers on its custom domain, on the `.vercel.app` alias that
 * existed before it, and - for a preview - on a hostname that did not exist
 * when the environment was configured. Only the canonical one is in
 * `BETTER_AUTH_URL`, so without the rest listed here, signing in anywhere else
 * fails with an origin error rather than a wrong password.
 *
 * `VERCEL_PROJECT_PRODUCTION_URL` and `VERCEL_URL` are set by the platform, so
 * preview deployments trust themselves without anybody adding a variable.
 */
export function trustedOrigins(): string[] {
  const found = [
    origin(appUrl()),
    origin(process.env.VERCEL_PROJECT_PRODUCTION_URL),
    origin(process.env.VERCEL_URL),
    ...(process.env.BETTER_AUTH_TRUSTED_ORIGINS ?? "").split(",").map(origin),
  ];
  return [...new Set(found.filter((value): value is string => Boolean(value)))];
}
